### ISSUE TITLE
OpenOCD support for NRF

### ISSUE THREAD

**Issue by lemmi** [tock/tockloader#19]
Hi,

with version 0.10.0, OpenOCD gained a couple of improvements for the NRF chips. I wrote a small script that is able to flash kernel and app bundles. Now I'm interested in adding support for openocd to tockloader, since openocd seems to be much more available than the jlink and it has support for different programmers aswell. Flashing an NRF via stlink is possible aswell.

So far my understanding it that I need to implement the [BoardInterface](/helena-project/tockloader/blob/master/tockloader/board_interface.py) for openocd. Is there anything else I need to take into consideration?

**Comment by cpluss** [comment]
@bradjc this would be nice, since openocd can be used to flash launchxl board as well (I think, still need to verify)

**Comment by alevy** [comment]
I agree that openocd would be nicer to support over JLink. It's easier to get openocd (at least on Linux)

**Comment by bradjc** [comment]
I'm all for adding openocd support and yes, implementing BoardInterface is
all that should be required. I'm not really sure how to use openocd and
what commands are required, but I can help with integrating the support
into tockloader.

>

**Comment by lemmi** [comment]
Ok, I'll dig out the script I use to flash the nrf51 and start on a prototype.

**Comment by bradjc** [comment]
I pushed a few commits that should make this easier. Really just need to implement `flash_binary`, `read_range`, `erase_page`, and `determine_current_board` for openocd; the other commands have default implementations.

We will need an `--openocd` flag to tell tockloader to use that channel. We may also need `--openocd-device` (not sure) and if so we may want to un-deprecate `--jtag-device` so that it can be used for any of the JTAG channels. Maybe we want an even more generic flag to specify the device, I'm not sure.
