### ISSUE TITLE
OpenOCD Flash Failure

### ISSUE THREAD

**Issue by LogoiLab** [tock/tockloader#53]
I am attempting to flash tock using the OpenOCD option in tockloader. I modified the Makefile to look like this:
```
TOCKLOADER_JTAG_FLAGS = --board nrf52dk --openocd --openocd-board /usr/share/openocd/scripts/board/nordic_nrf52_dk.cfg --debug
```
I get the following output:
```
text	   data	    bss	    dec	    hex	filename
 114176	   1708	 260436	 376320	  5be00	target/thumbv7em-none-eabi/release/nrf52840_dongle
sudo tockloader  flash --address 0x00000 --board nrf52dk --openocd --openocd-board /usr/share/openocd/scripts/board/nordic_nrf52_dk.cfg --debug target/thumbv7em-none-eabi/release/nrf52840_dongle.bin
Flashing binar(y|ies) to board...
Using known arch and jtag-device for known board nrf52dk
Running "openocd -c "source [find board/nordic_nrf52_dk.cfg]; init; reset init; halt; program /tmp/tmpuqe6n6cn.bin verify 0x0; soft_reset_halt; resume; exit"".
ERROR: openocd returned with error code 1
Open On-Chip Debugger 0.10.0+dev-01058-g853a05287 (2020-02-11-20:48)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Error: No J-Link device found.


openocd error
```
I have openocd configured to use an FTDI FT2232H mini module. I have also changed `--openocd-board` to point to the programmer interface config path as well, the same error persists.

System details:

- Linux 5.4.14
- OpenOCD 0.10.0

**Comment by bradjc** [comment]
Do you have a working `openocd` command that works without Tockloader? And how does that compare to what tockloader is running for you (`openocd -c "source [find board/nordic_nrf52_dk.cfg]; init; reset init; halt; program /tmp/tmpuqe6n6cn.bin verify 0x0; soft_reset_halt; resume; exit"`)?

Also, it looks like you may not want to pass `--board nrf52dk` since you are using the dongle.
